---
version: "3.6"

x-chain-adapter-def: &chain-adapter-def
  image: terra-adapter:0.0.1
  restart: on-failure
  networks:
    - terra

x-price-adapter-def: &price-adapter-def
  restart: on-failure
  environment:
    - "CACHE_ENABLED=true"
    - "EXPERIMENTAL_RATE_LIMIT_ENABLED=true"
    - "RATE_LIMIT_CAPACITY=60"
  networks:
    - terra

x-chainlink-node-def: &cl-node-def
  image: smartcontract/chainlink:0.10.3
  restart: on-failure
  depends_on:
    - postgres
  secrets:
    - node_password
    - apicredentials
  env_file:
    - ./chainlink.env
  volumes:
    - .:/host
  networks:
    - terra
  entrypoint:
    - chainlink
    - node
    - start
    - "-d"
    - "-p"
    - /run/secrets/node_password
    - "-a"
    - /run/secrets/apicredentials

x-ei-def: &ei-def
  image: terrademo/terra-ei
  command: '{\"name\":\"terra\",\"type\":\"terra\",\"url\":\"ws://terrad:26657/websocket\"}'
  depends_on:
    - postgres
  networks:
    - terra

services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      - POSTGRES_MULTIPLE_DATABASES=chainlink_1,chainlink_2,chainlink_3,ei_1,ei_2,ei_3,fcd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./LocalTerra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-init-scripts/postgres:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    networks:
      - terra

  terrad:
    image: terramoney/localterra-core:bombay
    pull_policy: always
    volumes:
      - ./LocalTerra/config:/root/.terra/config
    networks:
      - terra
    ports:
      - '26657:26657'
      - '26660:26660'
      - '1317:1317'
      - '9090:9090'
    command: terrad start

  fcd-collector:
    image: terramoney/fcd:bombay
    pull_policy: always
    depends_on:
      - terrad
      - postgres
    volumes:
      - ./LocalTerra/logs:/app/logs
    networks:
      - terra
    env_file: ./fcd.env
    command: collector

  oracle:
    image: terramoney/pseudo-feeder:bombay
    pull_policy: always
    depends_on:
      - terrad
    networks:
      - terra
    environment:
      TESTNET_LCD_URL: http://terrad:1317
    command: start

  fcd-api:
    image: terramoney/fcd:bombay
    pull_policy: always
    depends_on:
      - terrad
      - postgres
    volumes:
      - ./LocalTerra/logs:/app/logs
    networks:
      - terra
    ports:
      - "3060:3060"
    env_file: ./fcd.env
    command: start

  chainlink-node-1:
    <<: *cl-node-def
    ports:
      - "6691:6688"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/chainlink_1?sslmode=disable

  chainlink-node-2:
    <<: *cl-node-def
    ports:
      - "6692:6688"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/chainlink_2?sslmode=disable

  chainlink-node-3:
    <<: *cl-node-def
    ports:
      - "6693:6688"
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/chainlink_3?sslmode=disable

  external-initiator-1:
    <<: *ei-def
    environment:
      - EI_DATABASEURL=postgresql://postgres@postgres:5432/ei_1?sslmode=disable
      - EI_CHAINLINKURL=http://chainlink-node-1:6688/
      - TERRA_URL=http://terrad:1317
    env_file:
      - ./external_initiator1.env

  external-initiator-2:
    <<: *ei-def
    environment:
      - EI_DATABASEURL=postgresql://postgres@postgres:5432/ei_2?sslmode=disable
      - EI_CHAINLINKURL=http://chainlink-node-2:6688/
      - TERRA_URL=http://terrad:1317
    env_file:
      - ./external_initiator2.env

  external-initiator-3:
    <<: *ei-def
    environment:
      - EI_DATABASEURL=postgresql://postgres@postgres:5432/ei_3?sslmode=disable
      - EI_CHAINLINKURL=http://chainlink-node-3:6688/
      - TERRA_URL=http://terrad:1317
    env_file:
      - ./external_initiator3.env

  price-adapter-1:
    <<: *price-adapter-def
    image: public.ecr.aws/chainlink-staging/adapters/coingecko-adapter:develop-latest
    ports:
      - "8083:8080"

  price-adapter-2:
    <<: *price-adapter-def
    image: public.ecr.aws/chainlink-staging/adapters/cryptoapis-adapter:develop-latest
    ports:
      - "8084:8080"
    environment:
      # free keys, not security-critical, but need to be provided externally eventually
      - API_KEY=8752418fc8665de247def11dadf97aae7e3bb090

  price-adapter-3:
    <<: *price-adapter-def
    image: public.ecr.aws/chainlink-staging/adapters/cryptocompare-adapter:develop-latest
    ports:
      - "8085:8080"
    environment:
      - API_KEY=fec70f798ace5d55b5a329b6d17f881e20151c27acec5bc942884e0f9fa6720f

  chain-adapter-1:
    <<: *chain-adapter-def
    ports:
      - "8086:8080"
    environment:
      - FCD_URL=http://terrad:1317
      - CHAIN_ID=localterra
      - MNEMONIC=symbol force gallery make bulk round subway violin worry mixture penalty kingdom boring survey tool fringe patrol sausage hard admit remember broken alien absorb

  chain-adapter-2:
    <<: *chain-adapter-def
    ports:
      - "8087:8080"
    environment:
      - FCD_URL=http://terrad:1317
      - CHAIN_ID=localterra
      - MNEMONIC=quality vacuum heart guard buzz spike sight swarm shove special gym robust assume sudden deposit grid alcohol choice devote leader tilt noodle tide penalty

  chain-adapter-3:
    <<: *chain-adapter-def
    ports:
      - "8088:8080"
    environment:
      - FCD_URL=http://terrad:1317
      - CHAIN_ID=localterra
      - MNEMONIC=bounce success option birth apple portion aunt rural episode solution hockey pencil lend session cause hedgehog slender journey system canvas decorate razor catch empty
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
          - 9091:9090
    links:
      - terrad:terrad
    depends_on:
      - terrad
    networks:
      - terra
    restart: always
  terra-chainlink-exporter:
    image: terra-chainlink-exporter
    ports:
      - 8089:8089
    depends_on:
      - terrad
      - prometheus
    links:
      - terrad:terrad
    environment: 
      - TERRA_RPC=terrad:9090
      - TENDERMINT_RPC=http://terrad:26657
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    networks:
      - terra

volumes:
  pg: null
  cl: null
  chain: null
  prometheus_data: null
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials
networks:
  terra:
    driver: bridge
