---
version: '3'
services:
  chainlink:
    image: smartcontract/chainlink:0.10.3
    container_name: chainlink-node
    restart: on-failure
    ports:
      - '6688:6688'
    depends_on:
      - postgres
    secrets:
      - node_password
      - apicredentials
    env_file:
      - ./chainlink.env
    environment:
      - DATABASE_URL=postgresql://postgres@postgres:5432/chainlink?sslmode=disable
    volumes:
      - .:/host
    networks:
      - terra
    entrypoint:
      - chainlink
      - node
      - start
      - '-d'
      - '-p'
      - /run/secrets/node_password
      - '-a'
      - /run/secrets/apicredentials
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_MULTIPLE_DATABASES=chainlink,ei,fcd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./LocalTerra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-init-scripts/postgres:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    networks:
      - terra
  terrad:
    image: terramoney/localterra-core:bombay
    pull_policy: always
    volumes:
      - ./LocalTerra/config:/root/.terra/config
    networks:
      - terra
    ports:
      - '26657:26657'
      - '1317:1317'
    command: terrad start
  oracle:
    image: terramoney/pseudo-feeder:bombay
    pull_policy: always
    depends_on:
      - terrad
    networks:
      - terra
    environment:
      TESTNET_LCD_URL: http://terrad:1317
    command: start
  fcd-collector:
    image: terramoney/fcd:bombay
    pull_policy: always
    depends_on:
      - terrad
      - postgres
    volumes:
      - ./LocalTerra/logs:/app/logs
    networks:
      - terra
    env_file: ./fcd.env
    command: collector
  fcd-api:
    image: terramoney/fcd:bombay
    pull_policy: always
    depends_on:
      - terrad
      - postgres
    volumes:
      - ./LocalTerra/logs:/app/logs
    networks:
      - terra
    ports:
      - '3060:3060'
    env_file: ./fcd.env
    command: start
  coingecko-adapter:
    image: public.ecr.aws/chainlink-staging/adapters/coingecko-adapter:develop-latest
    container_name: coingecko-adapter
    restart: on-failure
    ports:
      - '8083:8080'
    networks:
      - terra
  external-adapter:
    image: terra-adapter:0.0.1
    container_name: external-adapter
    restart: on-failure
    ports:
      - '8084:8080'
    environment:
      - FCD_URL=http://terrad:1317
      - CHAIN_ID=localterra
      - MNEMONIC="satisfy adjust timber high purchase tuition stool faith fine install that you unaware feed domain license impose boss human eager hat rent enjoy dawn"
    networks:
      - terra
  external-initiator:
    image: terrademo/terra-ei
    container_name: external-initiator
    command: '{\"name\":\"terra\",\"type\":\"terra\",\"url\":\"ws://terrad:26657/websocket\"}'
    depends_on:
      - postgres
    environment:
      - EI_DATABASEURL=postgresql://ei@postgres:5432/ei?sslmode=disable
      - EI_CHAINLINKURL=http://chainlink-node:6688/
      - TERRA_URL=http://terrad:1317
    env_file:
      - ./external_initiator.env
    networks:
      - terra
volumes:
  pg: null
  cl: null
  chain: null
secrets:
  node_password:
    file: ./secrets/password.txt
  apicredentials:
    file: ./secrets/apicredentials
networks:
  terra:
    driver: bridge